### ISSUE TITLE
Can't change BaseLineSkip

### ISSUE THREAD

**Issue by keszocze** [FAU-AMMN/fau-beamer#16]
The main packages passes the `size` parameter to the font package as follows:

https://github.com/FAU-AMMN/fau-beamer/blob/e3f7cab2fb05a4aa487caac89e1cd3f90bedb18b/styles/beamerthemefau.sty#L56-L61

The option to pass the `baselineskip` as well is missing though. I propose to add the following to `beamerthemefau.sty`:
```latex
\DeclareOptionBeamer{BaseLineSkip}{%
	\PassOptionsToPackage{BaseLineSkip=#1}{styles/beamerfontthemefau}
}%
```

**Comment by TimRoith** [comment]
Thanks for spotting this, I incorporated your proposition in b11df5fed75d21a77ec7d23623013979564e7b15
