### ISSUE TITLE
Remove Debug Lines on Title Page

### ISSUE THREAD

**Issue by simonheilig** [FAU-AMMN/fau-beamer#19]
Hi,
I'm facing the problem of debug lines on the title page, see the following screenshot:
![image](https://user-images.githubusercontent.com/40565252/197519529-5b38a843-a18c-4f1e-9a22-2bda496de0fe.png)

I cloned the repo to Overleaf and they appeared right away.. Do you know how to remove them?

**Comment by TimRoith** [comment]
Hi, if I remember correctly this is a known issue of the PDF viewer in Overleaf. There are a few more PDF viewers that have issues with the beamercolorboxes that are used to place colored box. When I download the PDF from Overleaf and open the file in a regular viewer it looks fine. 

I hope this fixes your issue.

**Comment by simonheilig** [comment]
Using Firefox, Safari (MacOs 12.16) did not work for me, but Acrobat Reader managed to resolve this issue - thanks.
