### ISSUE TITLE
show notes on second screen

### ISSUE THREAD

**Issue by Stefan-FAU** [FAU-AMMN/fau-beamer#20]
Using `\setbeameroption{show notes on second screen}` results in layout problems on the title-page. The whole title-slide is slightly shifted to the right.

**Comment by TimRoith** [comment]
Hi, thanks for the hint. I rewrote the title page setup. In my recent test the shift should be gone, so I am going to close this issues.
If there are additional problems or the shift still appears I am going to reopen it.
