### ISSUE TITLE
Wrong footnote color

### ISSUE THREAD

**Issue by VChristlein** [FAU-AMMN/fau-beamer#21]
Hi, 

vielen Dank für das Package. Es scheint, dass die Footnote-Farbe falsch gesetzt ist. Auch bei dem Beispiel in main.pdf fehlt die Footnotemark und die Referenz wird nur gezeigt, da es sich um ne Referenz handelt, anderer Text ist einfach weiß. Liegt das nur an meinem System?

Viele Grüße,
Vincent

**Comment by TimRoith** [comment]
Danke für den Hinweis, die Farbe wurde tatsächlich falsch gesetzt. Das habe ich in 366773af4707b9b6bb4d5998f754ef592bf90d72 gefixt. Hoffe, dass es jetzt geht.

Grüße
Tim
