### ISSUE TITLE
Canvas size

### ISSUE THREAD

**Issue by VChristlein** [FAU-AMMN/fau-beamer#22]
Hi,

nochmals vielen Dank für dieses Paket und das schnelle Fixen des letzten Issues!
Ein neuer Vortrag ging problemlos zu erstellen. Ich wollte nun allerdings ein altes Tutorial umziehen und dabei ist mir aufgefallen, dass die Canvasgröße ca. dopelt so groß in jeder Dimension ist wie beim alten Template. Bei meiner neuen Präsentation habe ich entsprechend einfach die fontsize und baselineskip mittels der Optionen hochgedreht (die Defaultwerte sind viel zu klein). In meiner alten Präsentation befinden sich leider etliche Tikzgrafiken wo das nicht so leicht ist (und ich will nicht jede mit raisebox größer machen, es betrifft auch andere Werte, wie Linienbreiten, die nun dünner erscheinen). 

Wenn man sich den code in beamerthemefau.sty anschaut, sieht man dass die Werte anscheinend hard-gecoded sind anstatt die Defaultwerte des Beamer-packages zu verwenden. 

Wäre es möglich das zu fixen? 

So wurde es im alten FAU-Template gelöst: 
```tex
% Graphics
\pgfmathsetmacro{\beamer@aspectratio}{\beamer@paperwidth/\beamer@paperheight}
\pgfmathsetmacro{\beamer@fourtothree}{4/3}
\pgfmathsetmacro{\beamer@sixteentonine}{16/9}
\ifdim \beamer@aspectratio pt=\beamer@fourtothree pt% 
  % Aspect ratio 4:3
  \pgfdeclareimage[width=3.18cm]{faulogo-large}{art/\imagepath/\faulogo}
  \pgfdeclareimage[width=2.08cm]{faulogo-small}{art/\imagepath/\faulogo}
  \pgfdeclareimage[width=3.30cm,height=3.35cm]{seal-large}{art/\sealpath/fau-seal}
  \pgfdeclareimage[width=2.63cm,height=2.67cm]{seal-small}{art/\sealpath/fau-seal}
  \pgfdeclareimage[width=12.37cm,height=5.44cm]{image-large}{art/\imagepath/image-large-43}
  \pgfdeclareimage[width=12.37cm,height=3.59cm]{image-small}{art/\imagepath/image-small-43}

  % Convert 4:3 pptx dimensions to 4:3 beamer
  \def\factor{.503937}
  \def\factorx{.503937}
  \def\factory{.503937}
\else\ifdim \beamer@aspectratio pt=\beamer@sixteentonine pt% 
  % Aspect ratio 16:9
  \pgfdeclareimage[width=2.98cm]{faulogo-large}{art/\imagepath/\faulogo}
  \pgfdeclareimage[width=1.95cm]{faulogo-small}{art/\imagepath/\faulogo}
  \pgfdeclareimage[width=4.12cm,height=4.18cm]{seal-large}{art/\sealpath/fau-seal}
  \pgfdeclareimage[width=2.27cm,height=2.31cm]{seal-small}{art/\sealpath/fau-seal}
  \pgfdeclareimage[width=15.63cm,height=5.17cm]{image-large}{art/\imagepath/image-large-169}
  \pgfdeclareimage[width=15.63cm,height=3.39cm]{image-small}{art/\imagepath/image-small-169}

  % Convert 4:3 pptx dimensions to 16:9 beamer
  \def\factor{0.9375*.503937}
  \def\factorx{1.25*.503937}
  \def\factory{0.75*.503937}
\else%
  \errmessage{Any layout other than aspect ratio 4:3 or 16:9 is not supported}
\fi\fi%
``` 
Vielen Dank,
Vincent

**Comment by VChristlein** [comment]
Hi Tim, 

danke für deinen Einsatz! Ich glaube bei 16:9 passt es noch nicht, zumindest wird geometry bei 4:3 skaliert, aber noch nicht bei 16:9, s.: 
```tex
\ifthenelse{\equal{\aspectratio }{169}}{%
  \geometry{paperwidth=338.7mm,paperheight=190.5mm}% for 16:9
}{}%
\ifthenelse{\equal{\aspectratio }{43}}{%
  \geometry{paperwidth=\scale\dimexpr720pt,paperheight=\scale\dimexpr540pt}% for 4:3
}{}%
``` 
Wenn ich hier aber \scale einbaue passt es irgendwie auch nicht. Ich kann dir später mal ein Beispiel zum Testen schicken.

Vielen Dank und viele Grüße,
Vincent

**Comment by TimRoith** [comment]
Ja stimmt, es waren zwei Fehler drin, einmal den, den du oben schon gefixt hast, das habe ich jetzt eingebaut,
```tex
\ifthenelse{\equal{\aspectratio }{169}}{%
	\geometry{paperwidth=\scale\dimexpr338.7mm,paperheight=\scale\dimexpr190.5mm}% for 16:9
}{}%
```

und dann wurde bei 169 die falsche Option übergeben, das ist hier jetzt richtig

```tex
\PassOptionsToPackage{XScale=\scale}{styles/beamerouterthemefau}
\PassOptionsToPackage{YScale=\scale}{styles/beamerouterthemefau}
```

Das sollte jetzt beides klappen, den Font skaliere ich jetzt auch in `beamerfontthemefau.sty`

```tex
\FPeval{\globscale}{\fau@font@scale}
\FPeval{\fau@font@baselineskip}{\fau@font@scale * \fau@font@baselineskip}
\FPeval{\fontscale}{\fau@font@size/11}
\FPeval{\fontscale}{fontscale * globscale}
\FPupn{\fontscale}{0.442  fontscale * 2 round}
```

Es bleibt noch die Frage, ob bei 16:9 wie im alten template auch lieber

```tex
\PassOptionsToPackage{XScale=1.25\scale}{styles/beamerouterthemefau}
\PassOptionsToPackage{YScale=.75\scale}{styles/beamerouterthemefau}
```

gemacht werde soll. 

Grüße
Tim

**Comment by VChristlein** [comment]
Top, mit folgenden Einstellungen ist nun das Canvas und die Fontsize sehr ähnlich: 
```tex
fontsize=19,
scale=0.4725
``` 
Nur der baselineskip zwischen items passt noch nicht (atm leicht kleiner im alten Template), die Option 'BaseLineSkip' scheint im Moment nicht wirksam zu sein. Hier wäre ein Fix noch super!

Noch ein paar Anmerkungen: 
- `structure` ist (zumindest für TechFak) zu hell
- vielleicht noch caption anpassen, im alten Template war das: 
```
./beamerfontthemefau.sty:% Caption
./beamerfontthemefau.sty:\setbeamerfont{caption}{size=\scriptsize}
./beamercolorthemefau.sty:% Captions
./beamercolorthemefau.sty:\setbeamercolor{caption}{parent=structure}
./beamercolorthemefau.sty:\setbeamercolor{caption name}{parent=structure}
```

**Comment by TimRoith** [comment]
Ich hab die fontsize jetzt nochmal reskaliert, damit ```fontsize=11```, die standard größe ist.

Bei ```structure``` weiß ich nicht genau welche Farbe du meinst, weil Titel und Bullet Points haben schon die Farbe von ```structure```. Allgemein hab ich bei Farben nicht sooo viel Spielraum, weil das Template ja zu den Vorgaben des Corporate Design Teams passen muss.

**Comment by VChristlein** [comment]
Hi, 

danke, `fontbaselineskip=16` kommt sehr gut hin. Vielen Dank!
- `caption size`: okay, kann man ja vmtl auch individuell einstellen
- `structure`: stimmt, das kam mir bei dem Text irgendwie heller vor ;) , vielleicht wäre der Farbton wie bei der Linie angenehmer, aber das kann sich vmtl auch jeder selbst einstellen.
Wegen mir, kann dieses issue geschlossen werden. Vielen Dank nochmals!

Viele Grüße,
Vincent

**Comment by TimRoith** [comment]
Ja mit ```fontbaslineskip=16``` ist es dann zu viel für den Title. Hier ein Workaround:

Ich hab einen "mixed"-font hinzugefügt:

```tex
\newcommand{\LARGELarge}{\fontsize{\resultLARGEX}{\resultLargeY}\selectfont}
```

der nimmt die Schriftgröße ```LARGE``` aber den baselinewert von ```Large```. Du könntest dann in der Päamble  

```tex
\setbeamerfont{frametitle}{size=\LARGELarge, series=\bfseries}
```

hinzufügen. Ich hab das noch nicht per Default eingestellt.

Damit hat der FrameTitle Font dann eine kleiner Baseline und es sollte nicht drüber ragen.

**Comment by TimRoith** [comment]
Ich würde den Issue dann mal schließen, falls es noch Probleme gibt, gib gern Bescheid ;)

Grüße
Tim

**Comment by VChristlein** [comment]
Super, danke dir!
