### ISSUE TITLE
Including two logos in the Header

### ISSUE THREAD

**Issue by Linda-SophieSchneider** [FAU-AMMN/fau-beamer#23]
Hello and thanks for the template. Because many of us have two affiliations, we would like to be able two have at least two additional logos in the header. Therefore, we chose to place the logo like this on the title page to have enough space. Do you have any idea how to deal with two additional logos?
Thank you!
![grafik](https://user-images.githubusercontent.com/49022545/233658349-eba39da2-f631-40c3-9648-448a390dabf4.png)

**Comment by TimRoith** [comment]
Hi,
I added an option to have more Logos in the header. This is the default
<img width="359" alt="fb" src="https://user-images.githubusercontent.com/44805883/233749052-207eb3b6-d14f-49b3-8a05-c2252e03ddde.png">

Now we can use the option ```SecondLogo = template-art/FAUWortmarkeBlau.pdf``` which gives 

<img width="359" alt="fb1" src="https://user-images.githubusercontent.com/44805883/233749115-1b19959f-c6e6-4e38-a5bf-96b9418211e4.png">

And then  ```ThirdLogo = template-art/FAUWortmarkeBlau.pdf```

<img width="359" alt="fb2" src="https://user-images.githubusercontent.com/44805883/233749155-0724dda2-d696-48d3-9b79-1f1c75cfe845.png">

This also applies to the title of normal frames. It is not so clear to me, how to make the number of additional logos completely arbitrary, but for now you can at least add two additional logos. Hope this helps.

**Comment by TimRoith** [comment]
From my side this option works now, so I am going to close the issue. If there are further problems, don't hesitate to let me know.

Best
Tim

**Comment by Linda-SophieSchneider** [comment]
Thank you very much 😊😊
