### ISSUE TITLE
Turn of total page count

### ISSUE THREAD

**Issue by LeonhardRichter** [FAU-AMMN/fau-beamer#25]
It would be great to have the option to turn of the total page count in the corner, while keeping the current page number.

**Comment by TimRoith** [comment]
Hi thanks for noticing this. There was a small bug, actually the total page count should be turned off by default. Only the keyword ```InsertTotalFoot``` should activate it. I fixed it in the recent commit, if you don't want the total page count, you can now just remove this keyword, where the package is loaded.
